### ISSUE TITLE
Allow Users to Enter Comments for OTM Repository Commits

### ISSUE THREAD

**Issue by slivezey** [OpenTravel/OTM-DE-Compiler#15]
When a user commits changes to the OTM repository, they should be able to enter optional comments that describe the changes that are being submitted.

**Comment by pbenskin** [comment]
How do I vote for this? And can I vote multiple times?

**Comment by slivezey** [comment]
Done.  In addition to entering comments, the repository now maintains a history of all OTM files committed.
