### ISSUE TITLE
Object-Level Event Listeners for TLModel

### ISSUE THREAD

**Issue by slivezey** [OpenTravel/OTM-DE-Compiler#24]
Under the current TLModel design, listeners can be registered with the top-level TLModel to be notified of events that occur anywhere in the model.  This is useful in some scenarios, but others (particularly the GUI architecture) require a more fine-grained listener registration design.

The design should be updated to allow event listeners to be registered on any TLModelElement (BOs cores, attributes, indicators, etc.).  These fine-grained listeners will only be notified of events that occur on the object where the listener is registered.

The existing global event listener registration design should remain unchanged as a result of this enhancement.

**Comment by slivezey** [comment]
Done

**Comment by xmldave** [comment]
I am trying to change which LIbraryNode an top level object is associated with on a ownership event.  It seems like to do this using library ownership events I have to search the children/decedents to find one with matching TL object.  My node object is there but not accessible via either TLModelElement or Event. 

Doable but…what I think I want is one additional operation on the event or on the TLModelElement:
	event.getListeners();
	((TLModelElement)event.getAffectedItem()).getListeners();
I can then create listeners that will return their affected node.

**Comment by slivezey** [comment]
This has been implemented in the compiler and integrated into the OTM-DE GUI.
