### ISSUE TITLE
Common library not listed

### ISSUE THREAD

**Issue by xmldave** [OpenTravel/OTM-DE-Compiler#26]
The Opentravel common library is not listed in either the web or OTM-DE gui.  It can only be opened by opening libraries that include it (which are all of them). 

NS = http://www.opentravel.org/OTM/common/v0
Filename = Common_0_0_0.otm

I guessed that the problem is caused by the common library having the same root name as the namespace. So i put demo_0_0_0.otm  and Demo_0_0_0.otm in the demo namespace and they are viewed OK so perhaps this is not the reason.

**Comment by slivezey** [comment]
This issue seems to be resolved in the current release.  Closing.
