### ISSUE TITLE
Action Request and Response remove mime type fails

### ISSUE THREAD

**Issue by xmldave** [OpenTravel/OTM-DE-Compiler#32]
Both ActionRequest and ActionResponse use TLMime type in their internal data structures.The addMimeType uses TLMimeType enum while remove does not. Remove fails to find the object in the list of TLMimeTypes.

API would be easier to use if both add and remove used TLMimeType.

	public void removeMimeType(MimeType mimeType) {
		ModelEventBuilder eventBuilder = null;
		
		if (this.mimeTypes.contains(mimeType)) {

**Comment by slivezey** [comment]
Fixed
