### ISSUE TITLE
Deleting a Resource removes the business object from all elements that use it as a type

### ISSUE THREAD

**Issue by xmldave** [OpenTravel/OTM-DE-Compiler#36]
Create business object. Use that business object as the type of a property in another business object. Create resource with 1st BO then delete the BO. The type assignment in the 2nd business object is now missing (null) although the type name remains. The Type class is also set to null.

Because of the type class, i assumed it was a GUI side effect but it is really because an event was thrown against the property.
  Value Change event: TYPE_ASSIGNMENT_MODIFIED this = Player, old = Player, new = null

Here is the stack trace leading up the field modification done by the listener. There are no GUI classes involved.
> Type.set(Node, Node) line: 897	
PropertyNodeListener.processValueChangeEvent(ValueChangeEvent<?,?>) line: 49	
TLProperty(TLModelElement).publishEvent(ModelEvent<?>) line: 92	
TLProperty.setType(TLPropertyType) line: 185	
EntityRemovedIntegrityChecker$PurgeEntityVisitor.visitElement(TLProperty) line: 214	
ModelNavigator.navigateElement(TLProperty) line: 934	
ModelNavigator.navigateFacet(TLFacet) line: 838	
ModelNavigator.navigateBusinessObject(TLBusinessObject) line: 553	
ModelNavigator.navigateUserDefinedLibrary(TLLibrary) line: 359	
ModelNavigator.navigate(AbstractLibrary, ModelElementVisitor) line: 114	
ModelElementRemovedIntegrityChecker<S>(EntityRemovedIntegrityChecker<S,I>).purgeEntitiesFromModel(TLModelElement, TLModel) line: 82	
ModelElementRemovedIntegrityChecker<S>.processModelEvent(OwnershipEvent<S,TLModelElement>) line: 66	
ModelElementRemovedIntegrityChecker<S>.processModelEvent(ModelEvent) line: 33	
ModelIntegrityChecker(AbstractModelIntegrityChecker).processModelEvent(ModelEvent<Object>) line: 61	
TLModel.publishEvent(E) line: 461	
TLLibrary(TLModelElement).publishEvent(ModelEvent<?>) line: 87	
TLLibrary(AbstractLibrary).removeNamedMember(LibraryMember) line: 537	
TLLibrary.removeNamedMember(LibraryMember) line: 379	
ResourceNode.delete() line: 238

**Comment by slivezey** [comment]
Fixed
